import { RaidPost } from 'src/models/raid';

export const mockRaidPosts: RaidPost[] = [
  {
    id: 'raid-1',
    gameVersion: 'retail',
    raidName: 'Liberation of Undermine',
    difficulty: 'heroic',
    price: 2500000,
    faction: 'horde',
    server: 'area-52',
    poster: {
      id: 'user-1',
      name: 'Draven',
      avatar: '/static/images/avatars/1.jpg',
      credit: 150.5,
      karma: 245,
      isOnline: true
    },
    signups: 13,
    rolesNeeded: ['tank', 'healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 59 * 60 * 1000, // 59 mins ago
    avgPayTime: '3 Hours',
    payLimit: '30 Minutes'
  },
  {
    id: 'raid-2',
    gameVersion: 'retail',
    raidName: 'Nerub-ar Palace',
    difficulty: 'mythic',
    price: 8000000,
    faction: 'alliance',
    server: 'illidan',
    poster: {
      id: 'user-2',
      name: 'Shadowmend',
      avatar: '/static/images/avatars/2.jpg',
      credit: 320.0,
      karma: 890,
      isOnline: true
    },
    signups: 18,
    rolesNeeded: ['dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 25 * 60 * 1000,
    avgPayTime: '4 Hours',
    payLimit: '45 Minutes'
  },
  {
    id: 'raid-3',
    gameVersion: 'retail',
    raidName: 'Amirdrassil, the Dream\'s Hope',
    difficulty: 'normal',
    price: 450000,
    faction: 'horde',
    server: 'tichondrius',
    poster: {
      id: 'user-3',
      name: 'Frostweave',
      avatar: '/static/images/avatars/3.jpg',
      credit: 45.0,
      karma: 120,
      isOnline: false
    },
    signups: 5,
    rolesNeeded: ['tank', 'healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 2 * 60 * 60 * 1000,
    avgPayTime: '2 Hours',
    payLimit: '20 Minutes'
  },
  {
    id: 'raid-4',
    gameVersion: 'classic',
    raidName: 'Icecrown Citadel',
    difficulty: '25h',
    price: 1200000,
    faction: 'alliance',
    server: 'grobbulus',
    poster: {
      id: 'user-4',
      name: 'Lightbringer',
      avatar: '/static/images/avatars/4.jpg',
      credit: 89.5,
      karma: 340,
      isOnline: true
    },
    signups: 22,
    rolesNeeded: ['healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 15 * 60 * 1000,
    avgPayTime: '3 Hours',
    payLimit: '30 Minutes'
  },
  {
    id: 'raid-5',
    gameVersion: 'retail',
    raidName: 'Vault of the Incarnates',
    difficulty: 'lfr',
    price: 150000,
    faction: 'horde',
    server: 'zuljin',
    poster: {
      id: 'user-5',
      name: 'Stormrage',
      avatar: '/static/images/avatars/5.jpg',
      credit: 12.0,
      karma: 45,
      isOnline: true
    },
    signups: 2,
    rolesNeeded: ['tank', 'healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 3 * 60 * 60 * 1000,
    avgPayTime: '1 Hour',
    payLimit: '15 Minutes'
  },
  {
    id: 'raid-6',
    gameVersion: 'classic',
    raidName: 'Black Temple',
    difficulty: '25n',
    price: 800000,
    faction: 'horde',
    server: 'faerlina',
    poster: {
      id: 'user-6',
      name: 'Demonslayer',
      avatar: '/static/images/avatars/1.jpg',
      credit: 200.0,
      karma: 567,
      isOnline: false
    },
    signups: 15,
    rolesNeeded: ['tank', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 45 * 60 * 1000,
    avgPayTime: '2.5 Hours',
    payLimit: '25 Minutes'
  },
  {
    id: 'raid-7',
    gameVersion: 'retail',
    raidName: 'Liberation of Undermine',
    difficulty: 'mythic',
    price: 12000000,
    faction: 'alliance',
    server: 'stormrage',
    poster: {
      id: 'user-7',
      name: 'Mythiccarry',
      avatar: '/static/images/avatars/2.jpg',
      credit: 1250.0,
      karma: 2100,
      isOnline: true
    },
    signups: 19,
    rolesNeeded: ['dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 10 * 60 * 1000,
    avgPayTime: '5 Hours',
    payLimit: '60 Minutes'
  },
  {
    id: 'raid-8',
    gameVersion: 'retail',
    raidName: 'Aberrus, the Shadowed Crucible',
    difficulty: 'heroic',
    price: 1800000,
    faction: 'horde',
    server: 'area-52',
    poster: {
      id: 'user-8',
      name: 'Blazeclaw',
      avatar: '/static/images/avatars/3.jpg',
      credit: 78.0,
      karma: 189,
      isOnline: true
    },
    signups: 9,
    rolesNeeded: ['tank', 'healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 90 * 60 * 1000,
    avgPayTime: '3 Hours',
    payLimit: '30 Minutes'
  },
  {
    id: 'raid-9',
    gameVersion: 'classic',
    raidName: 'Ulduar',
    difficulty: '10h',
    price: 500000,
    faction: 'alliance',
    server: 'benediction',
    poster: {
      id: 'user-9',
      name: 'Titanforge',
      avatar: '/static/images/avatars/4.jpg',
      credit: 95.0,
      karma: 412,
      isOnline: false
    },
    signups: 7,
    rolesNeeded: ['healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 4 * 60 * 60 * 1000,
    avgPayTime: '2 Hours',
    payLimit: '20 Minutes'
  },
  {
    id: 'raid-10',
    gameVersion: 'retail',
    raidName: 'Sepulcher of the First Ones',
    difficulty: 'normal',
    price: 350000,
    faction: 'horde',
    server: 'malganis',
    poster: {
      id: 'user-10',
      name: 'Voidwalker',
      avatar: '/static/images/avatars/5.jpg',
      credit: 22.5,
      karma: 78,
      isOnline: true
    },
    signups: 4,
    rolesNeeded: ['tank', 'healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 5 * 60 * 60 * 1000,
    avgPayTime: '2.5 Hours',
    payLimit: '25 Minutes'
  },
  {
    id: 'raid-11',
    gameVersion: 'classic',
    raidName: 'Naxxramas',
    difficulty: '25n',
    price: 600000,
    faction: 'alliance',
    server: 'whitemane',
    poster: {
      id: 'user-11',
      name: 'Scourgebane',
      avatar: '/static/images/avatars/1.jpg',
      credit: 156.0,
      karma: 523,
      isOnline: true
    },
    signups: 12,
    rolesNeeded: ['tank', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 30 * 60 * 1000,
    avgPayTime: '3 Hours',
    payLimit: '30 Minutes'
  },
  {
    id: 'raid-12',
    gameVersion: 'retail',
    raidName: 'Nerub-ar Palace',
    difficulty: 'heroic',
    price: 3200000,
    faction: 'horde',
    server: 'thrall',
    poster: {
      id: 'user-12',
      name: 'Webspinner',
      avatar: '/static/images/avatars/2.jpg',
      credit: 445.0,
      karma: 1023,
      isOnline: true
    },
    signups: 16,
    rolesNeeded: ['healer', 'dps'],
    classesAllowed: 'all',
    postedAt: Date.now() - 20 * 60 * 1000,
    avgPayTime: '3.5 Hours',
    payLimit: '35 Minutes'
  }
];
